typography_spectrum: 0.38931888923980296
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.18724998808465898
  lightness: 0.556049540406093
  saturation: 0.6722162773367018
  rhythmicContrast: 0.4610292143188417
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.987983284983784
analytics:
  google: null
  facebook: null
  twitter: null
name: ArborMarketing
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Arbor Marketing Portfolio
purpose: []
